[general]
port = 6432
admin_username = "pgcat"
admin_password = "my-pony-likes-to-dance-tango"


[pools.my_database]


[pools.my_database.users.0]
pool_size = 5
username = "developer"
password = "very-secure-password"


[pools.my_database.shards.0]
database = "postgresml"
servers = [
    ["127.0.0.1", 5432, "primary"],
]
